module.exports.dummyRelatedData = [
  {
    id: '53425',
    campus: 'hr-sfo',
    name: 'reverse-jeggings',
    slogan: 'leetile a beetle',
    description: 'jeggings, but reverse',
    category: 'hats',
    default_price: '4.00',
    created_at: 'd',
    updated_at: 'r',
    features: [{
      feature: 'made of water',
      value: 'and wool',
    }],
  },
  {
    id: '53426',
    campus: 'hr-sfo',
    name: 'reverse-leggings',
    slogan: 'leetile a beetle',
    description: 'leggings, but reverse',
    category: 'hats',
    default_price: '4.00',
    created_at: 'd',
    updated_at: 'r',
    features: [{
      feature: 'made of water',
      value: 'and wool',
    }],
  },
  {
    id: '53427',
    campus: 'hr-sfo',
    name: 'eleben jeggings',
    slogan: 'leetile a beetle',
    description: 'jeggings, but eleven',
    category: 'hats',
    default_price: '4.00',
    created_at: 'd',
    updated_at: 'r',
    features: [{
      feature: 'made of water',
      value: 'and wool',
    }],
  },
  {
    id: '53428',
    campus: 'hr-sfo',
    name: 'normal jeggings',
    slogan: 'leetile a beetle',
    description: 'jeggings, nothing crazy.',
    category: 'hats',
    default_price: '4.00',
    created_at: 'd',
    updated_at: 'r',
    features: [{
      feature: 'made of water',
      value: 'and wool',
    }],
  },
  {
    id: '53429',
    campus: 'hr-sfo',
    name: 'totally jeggings',
    slogan: 'leetile a beetle',
    description: 'jeggings! really.',
    category: 'hats',
    default_price: '4.00',
    created_at: 'd',
    updated_at: 'r',
    features: [{
      feature: 'made of water',
      value: 'and wool',
    }],
  }
]